/* #undef BUILD_EMBREE_SHARED_LIB */
/* #undef RTCORE_RAY_MASK */
/* #undef RTCORE_STAT_COUNTERS */
/* #undef RTCORE_BACKFACE_CULLING */
#define RTCORE_INTERSECTION_FILTER
#define RTCORE_BUFFER_STRIDE
/* #undef RTCORE_SPINLOCKS */
/* #undef RTCORE_TASKLOGGER */
/* #undef RTCORE_EXPORT_ALL_SYMBOLS */
/* #undef RTCORE_ENABLE_RAYSTREAM_LOGGER */
/* #undef RTCORE_RETURN_SUBDIV_NORMAL */

